# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 988bbb61ddd59efa438d3e32d48b4228521ece8b947dcc46f6bfc094ff09a70b4805b98e7138ebbfe9600811b461ebcef34811fc94674390a161cf6f943a5422

test:
  secret_key_base: 892f6924a268117a5954bcad38b99fcba03f5ea776a16f4b9c72495e5cc42d09d3783ba965bf4489e7263f5b8c321021314eca2bbf29577083d6ab4d058b55b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
