class WelcomeController < ApplicationController
  def index 
    'jkldsfjkdfsjkldsfjkljkdflskjldsfjkldsfjkdfsjkdsf546========jkljklsdfjdsfjldfsjklfdslkjfdsjlfdsjljklsdfjklfsdjlkdsfjlklsdjkfjkljklsdfjdsfjldfsjklfdslkjfdsjlfdsjljklsdfjklfsdjlkdsfjlklsdjkfjkljklsdfjdsfjldfsjklfdslkjfdsjlfdsjljklsdfjklfsdjlkdsfjlklsdjkf'
  end
end
